type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/test_db?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password:
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
terminals: 1
works:
    work:
        serial: true
        active_terminals: 1
        rate: 1000
        weights: 100
transactiontypes:
    transactiontype:
        name: FeatureBench
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        create:
            - DROP TABLE IF EXISTS accounts;
            - CREATE TABLE accounts (id text NOT NULL ,name float,number text, PRIMARY KEY (id));
        cleanup:
            - DROP TABLE accounts;
        loadRules:
          - table: accounts
            rows: 10
            columns:
              - name: id
                util: PrimaryStringGen
                params:
                    - 1
                    - 2
              - name: name
                util: RandomFixedPoint
                params:
                    - 3
                    - 5.0
                    - 5.1
              - name: number
                util: RandomNstring
                params:
                    - 10
                    - 10






